import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import QueryClientProvider from "./QueryClientProvider";
import ThemeProvider from "./providers/ThemeProvider";
import { NavBar } from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Елаците-МЕД - АД - Анализ на данни и чат с ИИ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`} suppressHydrationWarning>
        <QueryClientProvider>
          <ThemeProvider>
            <div className="fixed top-0 left-0 right-0 z-50 bg-background">
              <NavBar />
            </div>
            <main className="flex-1 pt-16">{children}</main>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
